secret:
  # -- whether to create dexcom secret
  enabled: false
  data_:
    # -- plaintext Dexcom Oauth2 client id
    ClientId: ""
    # -- plaintext Dexcom Oauth2 client secret
    ClientSecret: ""
    # -- plaintext Dexcom Oauth2 state salt
    StateSalt: ""                            # the Dexcom client API url
configmap:
  enabled: true
  redirectURL: ""
nodeSelector: {}
tolerations: []
affinity: {}
