{{ if .Values.global.glooingress.enabled }}
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: user
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    app: tidepool
spec:
  routes:
  - matchers:
    - methods:
      - DELETE
      regex: /v1/users/[^/]+
    routeAction:
      single:
        upstream:
          name: user
          namespace: {{ .Release.Namespace }}
    options:
      timeout: "90s"
    - methods:
      - GET
      regex: /v1/users/[^/]+
    routeAction:
      single:
        upstream:
          name: user
          namespace: {{ .Release.Namespace }}
  - matchers:
    - methods:
      - GET
      prefix: /userservices/status
    routeAction:
      single:
        upstream:
          name: user
          namespace: {{ .Release.Namespace }}
    options:
      jwt:
        disable: true
      prefixRewrite: /status
  - matchers:
    - prefix: /userservices/
    routeAction:
      single:
        upstream:
          name: user
          namespace: {{ .Release.Namespace }}
    options:
      prefixRewrite: /
{{- end }}
