{{ if .Values.global.linkerdsupport.enabled }}
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: user.{{ .Release.Namespace }}.svc.cluster.local
  namespace: '{{ .Release.Namespace }}'
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /v1/users/[^/]+
    name: /v1/users/{id}_get_user
  - condition:
      method: DELETE
      pathRegex: /v1/users/[^/]+
    name: /v1/users/{id}_delete_user
{{- end }}
