{{ if or .Values.secret.enabled .Values.global.secret.generated -}}
---
apiVersion: v1
{{- with .Values.secret.data_ }}
data:
  ServiceAuth: {{ .ServiceAuth | default (randAlphaNum 40) | b64enc | quote  }}
  UserLongTermKey: {{ .UserLongTermKey | default (randAlphaNum 40) | b64enc  | quote }}
  UserMailVerification: {{ .UserMailVerification | default (randAlphaNum 40) | b64enc  | quote }}
  KeycloakClientSecret: {{ .KeycloakClientSecret | default (randAlphaNum 40) | b64enc  | quote }}
  KeycloakBackendClientSecret: {{ .KeycloakBackendClientSecret | default (randAlphaNum 40) | b64enc  | quote }}
  KeycloakAdminPassword: {{ .KeycloakAdminPassword | default (randAlphaNum 40) | b64enc  | quote }}
  KeycloakMigrationSecret: {{ .KeycloakMigrationSecret | default (randAlphaNum 40) | b64enc  | quote }}
{{- end }}
kind: Secret
metadata:
  name: shoreline
  namespace: {{ .Release.Namespace }}
  labels:
    app: shoreline
type: Opaque
{{- end }}
