apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
kubernetesVersion: v1.21.12
registry: ctlptl-registry
product: kind
kindV1Alpha4Cluster:
  name: tidepool-kind
  networking:
    ipFamily: ipv4
    apiServerAddress: 127.0.0.1
  nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 31500
      hostPort: 31500
      protocol: TCP
    - containerPort: 31501
      hostPort: 31501
      protocol: TCP
    - containerPort: 32500
      hostPort: 32500
      protocol: TCP
    - containerPort: 32000
      hostPort: 32000
      protocol: TCP
---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5000
