configmap:
  enabled: true
  redirectURL: ""
  tokenURL: ""
  authorizeURL: ""
  revokeURL: ""
  jwksURL: ""
  clientURL: ""
  scopes: ""
  partnerURL: ""
secret:
  enabled: false
  data_:
    ClientId: ""
    ClientSecret: ""
    StateSalt: ""
    PartnerId: ""
    PartnerSecret: ""
