{{ if .Values.enabled }}
{{- if .Values.global.glooingress.enabled }}
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: image
  namespace: "{{ .Release.Namespace }}"
  labels:
    namespace: "{{ .Release.Namespace }}"
    app: tidepool
spec:
  routes:
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: "/v1/users/[^/]+/images/.+"
    routeAction:
      single:
        upstream:
          name: image
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: "/v1/users/[^/]+/images"
    routeAction:
      single:
        upstream:
          name: image
  - matchers:
    - methods:
      - GET
      - PUT
      - DELETE
      prefix: "/v1/images"
    routeAction:
      single:
        upstream:
          name: image
{{- end }}
{{- end }}
