{{ if .Values.enabled }}
{{ if .Values.global.linkerdsupport.enabled }}
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: image.{{ .Release.Namespace }}.svc.cluster.local
  namespace: '{{ .Release.Namespace }}'
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /v1/users/[^/]+/images/.+
    name: /v1/users/{id}/images/.+_get_image
  - condition:
      method: POST
      pathRegex: /v1/users/[^/]+/images/.+
    name: /v1/users/{id}/images/.+_post_image
  - condition:
      method: DELETE
      pathRegex: /v1/users/[^/]+/images/.+
    name: /v1/users/{id}/images/.+_delete_image
  - condition:
      method: GET
      pathRegex: /v1/users/[^/]+/images
    name: /v1/users/{id}/images_get_image
  - condition:
      method: POST
      pathRegex: /v1/users/[^/]+/images
    name: /v1/users/{id}/images_post_image
  - condition:
      method: DELETE
      pathRegex: /v1/users/[^/]+/images
    name: /v1/users/{id}/images_delete_image
  - condition:
      method: GET
      pathRegex: /v1/images.*
    name: /v1/images_get_image
  - condition:
      method: PUT
      pathRegex: /v1/images.*
    name: /v1/images_put_image
  - condition:
      method: DELETE
      pathRegex: /v1/images.*
    name: /v1/images_delete_image
{{- end }}
{{- end }}
