{{ if .Values.secret.enabled -}}
---
apiVersion: v1
{{ with .Values.secret.data_ -}}
data:
  AppAPIKey: {{ .appAPIKey | default "" | b64enc | quote }}
  TrackAPIKey: {{ .trackAPIKey | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: customer-io
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
