{{ if .Values.secret.enabled -}}
---
apiVersion: v1
{{ with .Values.secret.data_ -}}
data:
  CustomerIOAppAPIKey: {{ .customerIOAppAPIKey | default "" | b64enc | quote }}
  CustomerIOTrackAPIKey: {{ .customerIOTrackAPIKey | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: customer-io
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
