apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: qae
  region: us-west-2
  version: "1.13"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 5
    ssh:
      publicKeyPath:  ~/.ssh/aws-tidepool-derrickburns.pub
    iam:
      withAddonPolicies:
        certManager: true

