configmap:
  enabled: false
  redirectURL: ""
  tokenURL: ""
  authorizeURL: ""
  revokeURL: ""
  scopes: ""
  jwksURL: ""
  serviceAccountIDs: ""
secret:
  enabled: false
  data_:
    clientId: ""
    clientSecret: ""
    stateSalt: ""
