{{ if .Values.secret.enabled -}}
---
apiVersion: v1
{{ with .Values.secret.data_ -}}
data:
  ClientId: {{ .clientId | default "" | b64enc | quote }}
  ClientSecret: {{ .clientSecret | default "" | b64enc | quote }}
  StateSalt: {{ .stateSalt | default "" | b64enc | quote }}
  PartnerSecret: {{ .partnerSecret | default "" | b64enc | quote }}
  JotformAPIKey: {{ .jotformAPIKey | default "" | b64enc | quote }}
  ShopifyClientId: {{ .shopifyClientId | default "" | b64enc | quote }}
  ShopifyClientSecret: {{ .shopifyClientSecret | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: oura
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
