---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: summary
{{ include "charts.labels.standard" .}}
  name: summary
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: "http"
    port: {{ .Values.global.ports.summary }}
    targetPort: "http"
  selector:
    app: summary
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
