{{ if .Values.global.glooingress.enabled }}
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: summary
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    app: tidepool
spec:
  routes:
  - matchers:
    - methods:
      - POST
      regex: /v1/users/[^/]+/summary
    routeAction:
      single:
        upstream:
          name: summary
    options:
      jwt:
        disable: true
  - matchers:
    - methods:
      - POST
      regex: /v1/clinics/[^/]+/summaries
    routeAction:
      single:
        upstream:
          name: summary
    options:
      jwt:
        disable: true
{{- end }}
