configmap:
  enabled: true
  acceptURL: ""
  authorizeURL: ""
  redirectURL: ""
  tokenURL: ""
  revokeURL: ""
  scopes: ""
  clientURL: ""
  partnerURL: ""
secret:
  enabled: false
  data_:
    clientId: ""
    clientSecret: ""
    stateSalt: ""
    partnerSecret: ""
