apiVersion: v1
description: A Helm chart for Kubernetes
name: mongo
version: 0.1.4
maintainers:
  - name: Derrick Burns
    email: derrick@tidepool.org
home: https://github.com/tidepool-org/development/charts
