{{ if .Values.global.kafka.connect.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    app: clinician-permissions-sink
    strimzi.io/cluster: {{ .Values.global.kafka.connect.clusterName }}
  name: clinician-permissions-sink
  namespace: {{ .Release.Namespace }}
spec:
  class: com.mongodb.kafka.connect.MongoSinkConnector
  config:
    change.data.capture.handler: com.mongodb.kafka.connect.sink.cdc.mongodb.ChangeStreamHandler
    collection: clinician_permissions
    connection.uri: ${file:/opt/kafka/external-configuration/connector-config/debezium-mongo-credentials.properties:Scheme}://${file:/opt/kafka/external-configuration/connector-config/debezium-mongo-credentials.properties:Username}:${file:/opt/kafka/external-configuration/connector-config/debezium-mongo-credentials.properties:Password}@${file:/opt/kafka/external-configuration/connector-config/debezium-mongo-credentials.properties:Addresses}/?ssl=true
    database: gatekeeper
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    post.processor.chain: com.mongodb.kafka.connect.sink.processor.AllowListValueProjector
    topics: {{ .Release.Namespace }}.clinic.clinicians
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    value.projection.list: _id,userId,clinicId,inviteId,permissions
    value.projection.type: AllowList
  tasksMax: {{ .Values.global.kafka.connect.sinkTasksMax | int }}
{{- end }}