{{ $discoveryNamespace := .Values.discovery.namespace | default .Release.Namespace }}
{{ $ports := .Values.global.ports }}
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: {{ .Values.routeTable.name }}
  namespace: {{ .Release.Namespace }}
spec:
  routes:
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: /v1/users/[^/]+/restricted_tokens
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: /v1/users/[^/]+/provider_sessions
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      regex: /v1/users/[^/]+/device_authorizations(/[^/]+)?
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - POST
      regex: /v1/device_authorizations
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /request-password-from-uploader
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: /v1/users/[^/]+/data_sources
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - PUT
      - DELETE
      regex: /v1/provider_sessions/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /verification-with-password
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - POST
      prefix: /event/csp-report/violation
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - DELETE
      regex: /v1/oauth/[^/]+/authorize
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      regex: /v1/users/[^/]+/data_sets
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
    options:
      timeout: "60s"
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: /v1/users/[^/]+/images/.+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-image-{{ $ports.image }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      regex: /v1/oauth/[^/]+/redirect
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      regex: /v1/users/[^/]+/datasets
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /request-password-reset
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /confirm-password-reset
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      regex: /v1/blobs/[^/]+/content
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blob-{{ $ports.blob }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - PUT
      - DELETE
      regex: /v1/data_sources/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: /v1/users/[^/]+/images
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-image-{{ $ports.image }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - PUT
      - DELETE
      prefix: /v1/restricted_tokens
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-auth-{{ $ports.auth }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      regex: /v1/users/[^/]+/blobs
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blob-{{ $ports.blob }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - DELETE
      regex: /v1/users/[^/]+/data
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - POST
      prefix: /v1/device/upload/cl
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-jellyfish-{{ $ports.jellyfish }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /email-verification
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /clinician-details
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /v1/device/data/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-jellyfish-{{ $ports.jellyfish }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /browser-warning
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - DELETE
      regex: /v1/blobs/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blob-{{ $ports.blob }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - PUT
      - DELETE
      regex: /v1/tasks/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-task-{{ $ports.task }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - DELETE
      regex: /v1/users/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-user-{{ $ports.user }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /v1/synctasks/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-jellyfish-{{ $ports.jellyfish }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - DELETE
      - PUT
      prefix: /v1/data_sets
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
    options:
      timeout: "60s"
  - matchers:
    - methods:
      - POST
      - PUT
      - DELETE
      prefix: /v1/datasets
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
    options:
      timeout: "60s"
  - matchers:
    - methods:
      - POST
      prefix: /serverlogin
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-shoreline-{{ $ports.shoreline }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - PUT
      - DELETE
      prefix: /v1/images
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-image-{{ $ports.image }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /patients
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      prefix: /v1/tasks
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-task-{{ $ports.task }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /profile
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /v1/time
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /export/
    options:
      timeout: '2m'
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-export-{{ $ports.export }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /access/status
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-gatekeeper-{{ $ports.gatekeeper }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /access/groups/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-gatekeeper-{{ $ports.gatekeeper }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      regex: /access/[^/]+/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-gatekeeper-{{ $ports.gatekeeper }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      regex: /access/[^/]+
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-gatekeeper-{{ $ports.gatekeeper }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /signup
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      prefix: /terms
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - POST
      prefix: /data/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-jellyfish-{{ $ports.jellyfish }}
          namespace: {{ $discoveryNamespace }}
    options:
      timeout: "60s"
  - matchers:
    - methods:
      - GET
      prefix: /info
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-jellyfish-{{ $ports.jellyfish }}
          namespace: {{ $discoveryNamespace }}
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /auth/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-shoreline-{{ $ports.shoreline }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
      timeout: '30s'
  - matchers:
    - methods:
      - GET
      prefix: /data/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-tide-whisperer-{{ $ports.tidewhisperer }}
          namespace: {{ $discoveryNamespace }}
    options:
      timeout: '1m'
      prefixRewrite: /
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /userservices/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-user-{{ $ports.user }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /metadata/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-seagull-{{ $ports.seagull }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
      retries:
        retryOn: '5xx'
        numRetries: 3
        perTryTimeout: '15s'
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /metrics/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-highwater-{{ $ports.highwater }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
      retries:
        retryOn: '5xx'
        numRetries: 3
        perTryTimeout: '15s'
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /confirm/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-hydrophone-{{ $ports.hydrophone }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
      timeout: '1m'
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /message/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-message-api-{{ $ports.messageapi }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
      timeout: '30s'
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /dataservices/
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-data-{{ $ports.data }}
          namespace: {{ $discoveryNamespace }}
    options:
      prefixRewrite: /
      timeout: "60s"
  - matchers:
    - methods:
      - GET
      prefix: /
    routeAction:
      single:
        upstream:
          name: {{ .Release.Namespace }}-blip-{{ $ports.blip }}
          namespace: {{ $discoveryNamespace }}
